data:
  gene_expressions_path: "local_data/processed/dream_five/net3_e-coli/gene_expression_data.tsv"
  transcription_factors_path: "local_data/processed/dream_five/net3_e-coli/transcription_factors.tsv"
  reference_network_path: "local_data/processed/dream_five/net3_e-coli/reference_network_data.tsv"

regressor:
  name: "LGBMRegressor"
  init_params:
